add graduate work version: 0.1
BolonkinAleksandr/java-explore-with-me pull request #2
Opened 2023-01-15 22:11 UTC by BolonkinAleksandr

2023-01-17 20:16 UTC, krylov-sergey-sergeevich requested changes
Привет, работа написана вроде как хорошо, но давай еще поработает и подшлифуем 

- Рекомендуется commit-message писать не просто для вида, а то что было действительно сделано.
- Отлично что логи сделаны на англ языке, это хорошая практика
- **Иногда в бд идет слишком много запросов вместо того чтобы запросить сразу для N объектов информацию идем и по одному просим** - важный пункт прошу глянуть самому вдруг еще где-то есть места такие
- В некоторых местах можно получше попытаться подумать и избежать дублирования кода, для нахождения таких мест рекомендую самому смотреть pr сверху вниз, а не через IDEA
- Подход с исключениями хорош, но можно лучше. Исключения если присмотреться похожи по структуре, не хочется ли создать структуру исключений или побольше кастомных исключений и не писать каждый раз весь текст причины исключения, а чисто название например NotFoundCategoryException extend NotFoundException это не обязательно, но как на подумать
- **Не обязательно сейчас,** но для развития на будущее: почитай про Swagger и Mapstruct
- @UtillityClass lombok  - удобная вспомогательная штука
- Давай создадим класс Constants и вынесем туда всякие константы

Буду ждать с доработками =) Если что пиши в пачке, если будут вопросы

2023-01-18 11:55 UTC, BolonkinAleksandr commented on ewm-service/pom.xml
> +            <artifactId>stats-server</artifactId>
Без нее поднимается только один контейнер, второй падает с такой ошибкой: org.postgresql.util.PSQLException: Connection to ewm-db:5432 refused.

2023-01-18 12:17 UTC, BolonkinAleksandr commented on ewm-service/pom.xml
> +            <artifactId>stats-server</artifactId>
Проблема была не в зависимости. Зависимость я удалил

2023-01-18 14:19 UTC, BolonkinAleksandr commented
Привет, Сергей!
Спасибо, за ревью. Поправил замечания.

2023-01-19 19:48 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

Удачи с дальнейшими работами =)

2023-04-13 12:41 UTC, merged